- name: Kubernetes HA Control Plane Start Remaining kube-vip static pods
  hosts: k8s_ha_masters
  become: yes
  tasks:
    - name: "Copy kube-vip.yaml manifest"
      copy:
        src: ./manifests/kube-vip.yaml
        dest: /etc/kubernetes/manifests/kube-vip.yaml
        force: true
