- name: Longhorn Storage Volumes
  hosts: ninja
  become: yes
  tasks:
    - name: Show device information
      parted: 
        device: "{{ item.device }}"
        unit: GiB
        state: info
      with_items: "{{ hostvars[inventory_hostname].lv_devices }}"
      register: disk_parted

    - name: Print device information
      debug:
        msg: System {{ inventory_hostname }} device {{ item.disk.dev }} size {{ item.disk.size }} partitions {{ item.partitions|length }}
      with_items: "{{ disk_parted['results'] }}"

    - name: Create a 3TB primary partition on sda
      parted:
        device: "{{ item.device }}"
        label: gpt
        number: "{{ item.partition }}"
        state: present
        align: optimal
        part_start: "-{{ item.size }}"
        part_end: "100%"
        fs_type: xfs
      with_items: "{{ hostvars[inventory_hostname].lv_devices }}"
      when: item.partition >0

    - name: Create an xfs file system on each new partition
      filesystem:
        state: present
        fstype: xfs
        dev: "{{ item.device }}{{ item.partition }}"
      with_items: "{{ hostvars[inventory_hostname].lv_devices }}"
      when: item.partition >0

    - name: Create the mount points
      file:
        path: "{{ item.path }}"
        state: directory
        mode: '0755'
      with_items: "{{ hostvars[inventory_hostname].lv_devices }}"

    - name: Automount
      mount:
        state: mounted
        boot: true
        fstype: "xfs"
        path: "{{ item.path }}"
        src: "{{ item.device }}{{ item.partition }}"
      with_items: "{{ hostvars[inventory_hostname].lv_devices }}"
      when: item.partition >0

