- name: Kubernetes HA Control Plane CNI Installation
  hosts: k8s_initial_master
  become: yes
  tasks:
#    - name: "Fetch the Calico CNI manifest"
#      get_url:
#        url: "https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/tigera-operator.yaml"
#        dest: /etc/kubernetes/manifests/tigera-operator.yaml
#        mode: "0644"
#        force: true
#
#    - name: "Install the Calico Tigera operator"
#      shell: kubectl create -f /etc/kubernetes/manifests/tigera-operator.yaml --kubeconfig=/etc/kubernetes/admin.conf
#
#    - name: "Fetch the Calico CNI manifest"
#      get_url:
#        url: "https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/custom-resources.yaml"
#        dest: /tmp/calico-resources.yaml
#        mode: "0644"
#        force: true
#
#    - name: "Configure Calico to use the correct pod subnet"
#      shell: "sed -i -e 's~cidr: 192.168.0.0/16~cidr: {{ kube_podnet }}~' /tmp/calico-resources.yaml"
#
#    - name: "Install the customized Calico manifest"
#      copy:
#        remote_src: true
#        src: /tmp/calico-resources.yaml
#        dest: /etc/kubernetes/manifests/calico-resources.yaml
#        mode: "0644"
#        force: true

    - name: "Install the Calico CNI"
      shell: kubectl create -f /etc/kubernetes/manifests/calico-resources.yaml --kubeconfig=/etc/kubernetes/admin.conf

#    - name: "Inspect the kubectl config"
#      shell: kubectl config view --kubeconfig=/etc/kubernetes/admin.conf
#      register: kube_config
#    - name: "Debug show kube config"
#      debug:
#        var: kube_config.stdout
#
